"""empty message

Revision ID: bc8c4904894b
Revises: 0448561e2d5a
Create Date: 2025-05-23 13:22:05.125031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8c4904894b'
down_revision = '0448561e2d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=240), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Media', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
